### ISSUE TITLE
Status ?

### ISSUE THREAD

**Issue by iangregsondev** [ignition-is-go/action-nx-affected-apps#2]
Hi,

Looks great, i was wondering at what status it is at ?

Is it something you will continue to develop ?

Is it being used in production ?

I was hoping to use something for deploying to docker hub and also for creating github releases

Thanks in advance

**Comment by kylebjordahl** [comment]
Hi @iangregsondev - We are using it in our workflow currently, but it's the first workflow that I created, and really doesn't reflect best practices. At some point in the future I hope to have time to improve the inner logic to utilize the modules provided by Github to better handle running CLI commands and parse the results (there's not a clear way to interact with the `nx affected` command via JS).

That being said, you're more than welcome to tinker with this, and I'll gladly look at any PRs you're willing to submit!

**Comment by iangregsondev** [comment]
Thanks @kylebjordahl, I will take a look later.
